# Generated by Django 6.0.6 on 2026-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_historicalregion_historicalrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestaurant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: mark as archived instead of deleting'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: mark as archived instead of deleting'),
        ),
    ]
