# Generated by Django 6.0.6 on 2026-06-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default="McDonald's Pakistan", max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('favicon', models.ImageField(blank=True, upload_to='favicon/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#DA291C', max_length=7)),
                ('secondary_color', models.CharField(default='#FFC72C', max_length=7)),
                ('accent_color', models.CharField(default='#27251F', max_length=7)),
            ],
            options={
                'verbose_name': 'Business Info',
                'verbose_name_plural': 'Business Info',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text="CSS class for icon (e.g. 'fab fa-facebook')", max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='core.businessinfo')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
    ]
