# Generated by Django 6.0.6 on 2026-07-14 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('audit_submitted', 'Audit Submitted'), ('ca_created', 'Corrective Action Created'), ('ca_completed', 'Corrective Action Completed'), ('ca_verified', 'Corrective Action Verified'), ('ca_closed', 'Corrective Action Closed'), ('ca_escalated', 'Corrective Action Escalated')], max_length=30)),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Receive email for this type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'constraints': [models.UniqueConstraint(fields=('user', 'notification_type'), name='unique_user_notification_type')],
            },
        ),
    ]
