# Generated by Django 6.0.6 on 2026-07-08 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='accent_color',
            field=models.CharField(default='#27251F', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-digit hex code (e.g. #DA291C).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='primary_color',
            field=models.CharField(default='#DA291C', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-digit hex code (e.g. #DA291C).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='secondary_color',
            field=models.CharField(default='#FFC72C', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-digit hex code (e.g. #DA291C).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='historicalbusinessinfo',
            name='accent_color',
            field=models.CharField(default='#27251F', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-digit hex code (e.g. #DA291C).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='historicalbusinessinfo',
            name='primary_color',
            field=models.CharField(default='#DA291C', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-digit hex code (e.g. #DA291C).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='historicalbusinessinfo',
            name='secondary_color',
            field=models.CharField(default='#FFC72C', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-digit hex code (e.g. #DA291C).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
