# Generated by Django 6.0.6 on 2026-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('auditor', 'Auditor'), ('manager', 'Manager'), ('restaurant_user', 'Restaurant User')], db_index=True, max_length=20, null=True),
        ),
    ]
