# Generated by Django 6.0.6 on 2026-07-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Send email copies of in-app notifications.', verbose_name='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Send email copies of in-app notifications.', verbose_name='Receive email notifications'),
        ),
    ]
