# Generated by Django 6.0.6 on 2026-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditquestionresponse',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo as evidence for this response', null=True, upload_to='audit_evidence/%Y/%m/', verbose_name='Evidence Photo'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Upload proof of completion', null=True, upload_to='corrective_action_evidence/%Y/%m/', verbose_name='Evidence Photo'),
        ),
        migrations.AddField(
            model_name='historicalauditquestionresponse',
            name='image',
            field=models.TextField(blank=True, help_text='Upload a photo as evidence for this response', max_length=100, null=True, verbose_name='Evidence Photo'),
        ),
        migrations.AddField(
            model_name='historicalcorrectiveaction',
            name='evidence_image',
            field=models.TextField(blank=True, help_text='Upload proof of completion', max_length=100, null=True, verbose_name='Evidence Photo'),
        ),
    ]
