# Generated by Django 6.0.6 on 2026-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auditquestionresponse_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittemplate',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Audit Template', 'verbose_name_plural': 'Audit Templates'},
        ),
        migrations.AddField(
            model_name='audit',
            name='auditee_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalaudit',
            name='auditee_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
