# Generated by Django 6.0.6 on 2026-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_audittemplate_options_audit_auditee_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditquestionresponse',
            name='is_answered',
            field=models.BooleanField(default=False, help_text='Whether this question has been answered/scored', verbose_name='Answered'),
        ),
        migrations.AddField(
            model_name='historicalauditquestionresponse',
            name='is_answered',
            field=models.BooleanField(default=False, help_text='Whether this question has been answered/scored', verbose_name='Answered'),
        ),
    ]
