# Generated by Django 6.0.6 on 2026-06-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auditquestionresponse_is_answered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='question_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='audits.auditquestionresponse'),
        ),
    ]
