# Generated by Django 6.0.6 on 2026-06-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_add_ca_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: mark as archived instead of deleting'),
        ),
        migrations.AddField(
            model_name='historicalaudit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete: mark as archived instead of deleting'),
        ),
    ]
